server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}
  rootPath: /api/
  requestLog:
      appenders:
        - type: file
          currentLogFilename: ./logs/access.log
          threshold: ALL
          archive: true
          archivedLogFilenamePattern: ./logs/access-%d.log
          archivedFileCount: 5
          timeZone: UTC
dataSourceFactory:
  driverClass: org.postgresql.Driver
  user: uom
  url: jdbc:postgresql://${DATABASE_HOST:-localhost}/${DATABASE:-uom}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
logging:
  appenders:
    - type: console
    # logformat: <Level> - <Time> - <Revision> - <Environment> - <Thread> - <Log Content>
      logFormat: "%level %d{HH:mm:ss.SSS} %mdc{revision} %mdc{environment} '%mdc{user}' %t %logger{5} - %X{code} %msg %n"
      threshold: INFO
      target: stderr
    - type: file
      logFormat: "%level %d{HH:mm:ss.SSS} %mdc{revision} %mdc{environment} '%mdc{user}' %t %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/app.log
      archivedLogFilenamePattern: ./logs/app-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
iibUrl: ${IIB_URL:-http://localhost:8001}