orchestrator:
  build: api/
  environment:
    - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
    - http_proxy=http://corppx.sysco.com:80
    - https_proxy=http://corppx.sysco.com:80
    - HTTP_PROXY=http://corppx.sysco.com:80
    - HTTPS_PROXY=http://corppx.sysco.com:80
  ports:
    - '8080:8080'
    - '8081:8081'