server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8885}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8886}
  rootPath: /orchestrator/
  requestLog:
      appenders:
        - type: file
          currentLogFilename: ./logs/access.log
          threshold: ALL
          archive: true
          archivedLogFilenamePattern: ./logs/access-%d.log
          archivedFileCount: 5
          timeZone: UTC
logging:
  appenders:
    - type: console
    # logformat: <Level> - <Time> - <Revision> - <Environment> - <Thread> - <Log Content>
      logFormat: "%level %d{HH:mm:ss.SSS} %mdc{revision} %mdc{environment} '%mdc{user}' %t %logger{5} - %X{code} %msg %n"
      threshold: INFO
      target: stderr
    - type: file
      logFormat: "%level %d{HH:mm:ss.SSS} %mdc{revision} %mdc{environment} '%mdc{user}' %t %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/app.log
      archivedLogFilenamePattern: ./logs/app-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
orderServiceUrl: ${ORDER_SERVICE_URL:-http://localhost:8080}